import "./css/style.css";

import { Inter } from "next/font/google";

import Header from "@/components/ui/header";
import Banner from "@/components/banner";
import { Suspense } from "react";

import { Analytics } from "@vercel/analytics/react";
import GoogleAnalytics from "@/components/googleanalytics";
import Script from "next/script";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <Analytics />
        <Suspense>
          <GoogleAnalytics />
        </Suspense>
        <Script
          defer
          data-domain="vontane.com"
          src="https://plausible.io/js/script.js"
        ></Script>

        <title>Vontane Content Editor </title>
        <meta
          name="description"
          content="Vontane AI Writer, AI Text to Speech"
        />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />

        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />

        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />

        <meta property="og:title" content="Vontane Content Editor" />
        <meta
          property="og:description"
          content="Vontane AI Writer, AI Text to Speech"
        />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://www.vontane.com" />

        <link rel="icon" href="/favicon.ico" />
      </head>
      <body
        className={`${inter.variable} font-inter antialiased bg-white text-gray-900 tracking-tight`}
      >
        <div className="Simpleflex flex-col min-h-screen overflow-hidden supports-[overflow:clip]:overflow-clip">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
